# -*- coding: utf-8 -*-
"""Veri_Bilimi_Donem_Projesi_MAGIC_Gamma_Telescope.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HpVjBDCu_91ZlriskFHyzBB5s9V6a8gD
"""

# 1. KÜTÜPHANELER VE VERİYİ İÇERİ AKTARMA

# Temel Veri İşleme ve Matematik Kütüphaneleri
import pandas as pd
import numpy as np
import tensorflow as tf

# Görselleştirme Kütüphaneleri
import matplotlib.pyplot as plt
import seaborn as sns

# Uyarıları gizlemek için (Çıktıların temiz görünmesi için)
import warnings
warnings.filterwarnings('ignore')

# Tekrarlanabilirlik (Reproducibility) için rastgelelik tohumlarını sabitleme
np.random.seed(42)
tf.random.set_seed(42)

print("Kütüphaneler başarıyla yüklendi!")

# Veri setini çekme ve sütunları isimlendirme
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/magic/magic04.data'
sutun_isimleri = [
    'fLength', 'fWidth', 'fSize', 'fConc', 'fConc1', 'fAsym',
    'fM3Long', 'fM3Trans', 'fAlpha', 'fDist', 'class'
]
df = pd.read_csv(url, names=sutun_isimleri)

# Hedef değişkeni sayısallaştırma (Gamma = 1, Hadron = 0)
df['class'] = df['class'].map({'g': 1, 'h': 0})

print("Veri seti başarıyla yüklendi!")
print("2. Veri Seti Bilgileri:")
print("Veri Seti Boyutu:", df.shape)
print("\nSınıf Dağılımı (1: Gama, 0: Hadron):")
print(df['class'].value_counts())

print("\nVeri Setindeki Eksik Değerlerin Kontrolü:\n")
eksik_veri = df.isnull().sum().sum()
if eksik_veri == 0:
    print("Veri setinde eksik değer bulunmamaktadır")
else:
    print(f"Veri setinde toplam {eksik_veri} eksik değer bulundu!")


# KORELASYON ISI HARİTASI (EDA)
# Değişkenlerin birbiriyle ve hedef değişkenle olan ilişkisini görmek için Isı Haritası (Heatmap)
plt.figure(figsize=(12, 8))
# Sadece özelliklerin arasındaki ilişkiye bakıyoruz (korelasyon)
sns.heatmap(df.corr(), annot=True, cmap='coolwarm', fmt=".2f", linewidths=0.5)
plt.title('Özellikler Arası Korelasyon Isı Haritası (Correlation Heatmap)', fontsize=15)
plt.show()

# 2. VERİ BÖLME VE ÖLÇEKLENDİRME (PREPROCESSING)
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Özellikler (X) ve Hedef Değişken (y) ayrımı
X = df.drop('class', axis=1)
y = df['class']

# Sınıf dengesini (stratify) koruyarak %80 Eğitim, %20 Test bölmesi
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

# SVM ve k-NN gibi algoritmalar için veriyi standartlaştırma
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print("Veri %80 Eğitim ve %20 Test olarak bölündü ve ölçeklendirildi.")

# 3. HİPERPARAMETRE OPTİMİZASYONU (k-NN İÇİN)

from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import cross_val_score

print("k-NN için 1'den 20'ye kadar komşu sayıları test ediliyor...")
k_degerleri = range(1, 21)
knn_skorlari = []
best_k = 1
max_knn_skor = 0


for k in k_degerleri:
    knn = KNeighborsClassifier(n_neighbors=k)
    skor = cross_val_score(knn, X_train_scaled, y_train, cv=5, scoring='accuracy').mean()
    knn_skorlari.append(skor)
    if skor > max_knn_skor:
        max_knn_skor = skor
        best_k = k

print(f"Testler sonucunda en iyi komşu sayısı (k) = {best_k} olarak belirlendi.\n")

# Optimizasyon Grafiği
plt.figure(figsize=(8, 4))
plt.plot(k_degerleri, knn_skorlari, marker='o', linestyle='dashed', color='green')
plt.title('k-NN Algoritması: Komşu Sayısına (k) Göre Doğruluk Değişimi')
plt.xlabel('k Değeri')
plt.ylabel('Test Doğruluğu')
plt.xticks(k_degerleri)
plt.grid(True, alpha=0.5)
plt.show()

"""k-NN Algoritmasında k Değerinin Seçimi Hakkında Not:

İkili sınıflandırma (0 ve 1) yapılan projelerde berabere kalma (tie) durumunu önlemek için k değerinin genelde tek sayı seçilmesi önerilir. Ancak analizimizde optimizasyon sonucu en iyi değer çift sayı çıkmıştır.
Scikit-Learn kütüphanesi bu durumu çözebilecek bir yapıya sahip olduğu için çift sayı kullanılmasında sorun olmamıştır.
"""

# 4. KLASİK SINIFLANDIRMA ALGORİTMALARININ KIYASLANMASI

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score, roc_auc_score
from sklearn.model_selection import StratifiedKFold, cross_val_score
import pandas as pd

# Eğer 3. bölümü çalıştırmadıysan çökmemesi için güvenlik önlemi
if 'best_k' not in locals():
    best_k = 5

# Modellerin Sözlük İçinde Tanımlanması (HIZLANDIRILMIŞ VERSİYON)
modeller = {
    "Lojistik Regresyon": LogisticRegression(),
    f"k-En Yakın Komşu (k={best_k})": KNeighborsClassifier(n_neighbors=best_k),
    "Karar Ağacı (Gini)": DecisionTreeClassifier(criterion='gini', random_state=42),
    "Karar Ağacı (Entropi)": DecisionTreeClassifier(criterion='entropy', random_state=42),
    "Rastgele Orman": RandomForestClassifier(n_estimators=100, random_state=42),
    "Basit Bayes (Naive Bayes)": GaussianNB(),
}

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

# Kod Kalitesi: İşlemleri tekrar kullanılabilir bir fonksiyon içine alıyoruz
def modelleri_karsilastir_ve_raporla(modeller_dict, X_train, y_train, X_test, y_test, cv_kfold):
    print("Algoritmalar eğitiliyor ve Çapraz Doğrulama (CV) uygulanıyor...")
    sonuclar = []
    auc_sonuclar = []

    for isim, model in modeller_dict.items():
        # Test Skoru Hesaplamaları
        model.fit(X_train, y_train)
        y_pred = model.predict(X_test)

        # Çapraz Doğrulama (CV) Skoru Hesaplama
        cv_skorlari = cross_val_score(model, X_train, y_train, cv=cv_kfold, scoring='accuracy')

        sonuclar.append({
            "Algoritma": isim,
            "CV Doğruluk (Ort)": round(cv_skorlari.mean(), 4),
            "CV Std. Sapma": round(cv_skorlari.std(), 4),
            "Test Doğruluk": round(accuracy_score(y_test, y_pred), 4),
            "Hassasiyet": round(precision_score(y_test, y_pred), 4),
            "Duyarlılık": round(recall_score(y_test, y_pred), 4),
            "F1-Skoru": round(f1_score(y_test, y_pred), 4)
        })

        # ROC-AUC Olasılık Hesaplaması
        if hasattr(model, "predict_proba"):
            probs = model.predict_proba(X_test)[:, 1]
            auc_sonuclar.append({
                "Algoritma": isim,
                "ROC-AUC Skoru": round(roc_auc_score(y_test, probs), 4)
            })

    # DataFrameleri oluştur ve döndür
    df_sonuc = pd.DataFrame(sonuclar).sort_values(by="Test Doğruluk", ascending=False).reset_index(drop=True)
    df_auc = pd.DataFrame(auc_sonuclar).sort_values("ROC-AUC Skoru", ascending=False).reset_index(drop=True)
    return df_sonuc, df_auc

# Fonksiyonu Çağırıyoruz
sonuclar_df, auc_df = modelleri_karsilastir_ve_raporla(modeller, X_train_scaled, y_train, X_test_scaled, y_test, cv)

# Çıktıları Ekrana Basıyoruz
display(sonuclar_df)
print("\nTÜM MODELLER İÇİN ROC-AUC KIYASLAMASI")
display(auc_df)



# ÖZGÜN DEĞER: SMOTE İLE SINIF DENGESİZLİĞİNİ GİDERME VE MODEL KIYASLAMASI

from imblearn.over_sampling import SMOTE
from imblearn.pipeline import Pipeline as ImbPipeline
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
import seaborn as sns

print("\nÖZGÜN DEĞER 1: SMOTE İLE DENGESİZ VERİ ANALİZİ (GELİŞMİŞ KIYASLAMA)\n")

print(f"SMOTE Öncesi Eğitim Seti Dağılımı:\n{y_train.value_counts()}")

# 1. SMOTE Uygulaması
smote = SMOTE(random_state=42)
X_train_smote, y_train_smote = smote.fit_resample(X_train_scaled, y_train)

print(f"\nSMOTE Sonrası Eğitim Seti Dağılımı:\n{y_train_smote.value_counts()}")


# 2. Modellerin Tanımlanması (Lojistik Regresyon, k-NN, Rastgele Orman)
smote_modeller = {
    "Logistic Regression": LogisticRegression(random_state=42),
    f"K-Nearest Neighbors (k={best_k})": KNeighborsClassifier(n_neighbors=best_k),
    "Random Forest": RandomForestClassifier(n_estimators=100, random_state=42)
}

smote_sonuclar = []
rf_y_pred_smote = None # Karmaşıklık matrisi için saklayacağız

for isim, model in smote_modeller.items():
    # 1. SMOTE Öncesi Eğitim (Orijinal Veri)
    model.fit(X_train_scaled, y_train)
    y_pred_normal = model.predict(X_test_scaled)

    smote_sonuclar.append({
        "Model": isim,
        "Durum": "Orijinal (SMOTE Öncesi)",
        "Doğruluk": accuracy_score(y_test, y_pred_normal),
        "Precision (Hadron)": precision_score(y_test, y_pred_normal, pos_label=0),
        "Recall (Hadron)": recall_score(y_test, y_pred_normal, pos_label=0),
        "F1-Skoru (Genel)": f1_score(y_test, y_pred_normal, average='weighted')
    })

    # 2. SMOTE Sonrası Eğitim (Dengelenmiş Veri - PIPELINE İLE TUTARLI YAPI)
    smote_pipe = ImbPipeline([
        ('smote', SMOTE(random_state=42)),
        ('classifier', model)
    ])
    smote_pipe.fit(X_train_scaled, y_train)
    y_pred_smote = smote_pipe.predict(X_test_scaled)

    # Random Forest'ın SMOTE tahminlerini görselleştirme için kaydediyoruz
    if isim == "Random Forest":
        rf_y_pred_smote = y_pred_smote

    smote_sonuclar.append({
        "Model": isim,
        "Durum": "Dengelenmiş (SMOTE Sonrası)",
        "Doğruluk": accuracy_score(y_test, y_pred_smote),
        "Precision (Hadron)": precision_score(y_test, y_pred_smote, pos_label=0),
        "Recall (Hadron)": recall_score(y_test, y_pred_smote, pos_label=0),
        "F1-Skoru (Genel)": f1_score(y_test, y_pred_smote, average='weighted')
    })

# Sonuçları DataFrame'e çevirme
df_smote_kiyas = pd.DataFrame(smote_sonuclar)
print("\nSMOTE'un Farklı Modeller Üzerindeki Etkisi:")
display(df_smote_kiyas.round(4))


import numpy as np
import matplotlib.pyplot as plt

# Karşılaştırılacak Metrikler ve Başlıkları
metrikler = ["Doğruluk", "Precision (Hadron)", "Recall (Hadron)", "F1-Skoru (Genel)"]
metrik_etiketler = ["Doğruluk\n(Accuracy)", "Precision\n(Hadron)", "Recall\n(Hadron)", "F1-Skoru\n(Genel)"]

# Her model için önce / sonra değerleri çekiyoruz
model_isimleri = df_smote_kiyas["Model"].unique()

n_model = len(model_isimleri)   # 3 model
n_metrik = len(metrikler)       # 4 metrik

fig, axes = plt.subplots(1, n_metrik, figsize=(18, 5))
fig.suptitle("SMOTE Öncesi ve Sonrası Model Performans Karşılaştırması", fontsize=15, fontweight='bold', y=1.02)

renkler = {
    "Orijinal (SMOTE Öncesi)":    "#5B9BD5",   # Mavi
    "Dengelenmiş (SMOTE Sonrası)": "#ED7D31",  # Turuncu
}

bar_genisligi = 0.35
x = np.arange(n_model)

for ax_idx, (metrik, etiket) in enumerate(zip(metrikler, metrik_etiketler)):
    ax = axes[ax_idx]

    oncesi_degerler = []
    sonrasi_degerler = []

    for model in model_isimleri:
        satir_once = df_smote_kiyas[
            (df_smote_kiyas["Model"] == model) &
            (df_smote_kiyas["Durum"] == "Orijinal (SMOTE Öncesi)")
        ][metrik].values[0]

        satir_sonra = df_smote_kiyas[
            (df_smote_kiyas["Model"] == model) &
            (df_smote_kiyas["Durum"] == "Dengelenmiş (SMOTE Sonrası)")
        ][metrik].values[0]

        oncesi_degerler.append(satir_once)
        sonrasi_degerler.append(satir_sonra)

    bars1 = ax.bar(x - bar_genisligi/2, oncesi_degerler,
                   width=bar_genisligi, label="SMOTE Öncesi",
                   color=renkler["Orijinal (SMOTE Öncesi)"],
                   alpha=0.88, edgecolor='white', linewidth=0.6)

    bars2 = ax.bar(x + bar_genisligi/2, sonrasi_degerler,
                   width=bar_genisligi, label="SMOTE Sonrası",
                   color=renkler["Dengelenmiş (SMOTE Sonrası)"],
                   alpha=0.88, edgecolor='white', linewidth=0.6)

    # Değerleri çubukların üstüne yaz
    for bar in bars1:
        ax.text(bar.get_x() + bar.get_width() / 2,
                bar.get_height() + 0.005,
                f"{bar.get_height():.3f}",
                ha='center', va='bottom', fontsize=8, color='#333333')

    for bar in bars2:
        ax.text(bar.get_x() + bar.get_width() / 2,
                bar.get_height() + 0.005,
                f"{bar.get_height():.3f}",
                ha='center', va='bottom', fontsize=8, color='#333333')

    # Fark oklarını çiz (Performans artış/düşüşünü görselleştir)
    for i, (once, sonra) in enumerate(zip(oncesi_degerler, sonrasi_degerler)):
        fark = sonra - once
        renk = "#27AE60" if fark >= 0 else "#E74C3C"  # Yeşil (Artış), Kırmızı (Düşüş)
        isaretci = "▲" if fark >= 0 else "▼"
        ax.annotate(f"{isaretci} {abs(fark):.3f}",
                    xy=(x[i], max(once, sonra) + 0.03),
                    ha='center', va='bottom',
                    fontsize=8, color=renk, fontweight='bold')

    # Eksen ayarları ve İsimlendirmeler
    ax.set_xticks(x)

    # model_isimleri dinamik olduğu için isimleri otomatik alıyoruz (hata önleyici)
    kisa_isimler = [isim.split('(')[0].strip() for isim in model_isimleri]
    ax.set_xticklabels(kisa_isimler, fontsize=9, rotation=15)

    ax.set_title(etiket, fontsize=11, fontweight='bold', pad=8)
    ax.set_ylim(0.0, 1.15)  # Eksenleri %0 ile %115 (oklar sığsın diye) arasına çektik
    ax.set_ylabel("Skor", fontsize=9)
    ax.grid(axis='y', linestyle='--', alpha=0.4)
    ax.spines[['top', 'right']].set_visible(False)

    # Lejant sadece ilk grafikte görünsün
    if ax_idx == 0:
        ax.legend(fontsize=9, loc='lower center', bbox_to_anchor=(0.5, -0.3))

plt.tight_layout()
plt.show()

# 3. SMOTE Sonrası Rastgele Orman için Karmaşıklık Matrisi (Confusion Matrix)
plt.figure(figsize=(6, 5))
sns.heatmap(confusion_matrix(y_test, rf_y_pred_smote), annot=True, fmt='d', cmap='Reds')
plt.title('SMOTE Sonrası Lider Model (RF) Karmaşıklık Matrisi', fontsize=12)
plt.xlabel('Tahmin Edilen Sınıf')
plt.ylabel('Gerçek Sınıf')
plt.show()

print("YORUM: SMOTE kullanımı sadece tek bir modelde değil, Lojistik Regresyon ve KNN üzerinde de denenmiş ve özellikle azınlık sınıfı olan Hadron'u (0) yakalama (Recall) oranlarında gözle görülür bir artış sağlanmıştır.")

"""**Sınıf Dengesizliği Üzerine Değerlendirme:**
Veri setimizde Gama sınıfı (12.332), Hadron sınıfından (6.688) yaklaşık 2 kat daha fazla olduğu için veri setinde bir "Sınıf Dengesizliği" söz konusudur. Bu nedenle, modellerin başarısını değerlendirirken yalnızca genel 'Doğruluk (Accuracy)' metriğine değil; dengesiz veri setlerinde asıl kaliteyi gösteren 'F1-Skoru' ve 'Duyarlılık (Recall)' metriklerine de büyük ağırlık verilmiştir. Rastgele Orman modeli bu kritik metriklerde de en yüksek performansı sergilemiştir.
"""

# 5. EN İYİ MODELİN (RASTGELE ORMAN) İLERİ SEVİYE ANALİZİ VE OPTİMİZASYONU

from sklearn.model_selection import RandomizedSearchCV
from sklearn.metrics import confusion_matrix, roc_curve, roc_auc_score, classification_report

print("RASTGELE ORMAN: VARSAYILAN VE OPTİMİZE EDİLMİŞ MODEL KIYASLAMASI")


from imblearn.pipeline import Pipeline as ImbPipeline

# ADIM 1: VARSAYILAN (DEFAULT) MODELİN EĞİTİLMESİ (Adil kıyaslama için Pipeline ile)
rf_default_pipe = ImbPipeline([
    ('smote', SMOTE(random_state=42)),
    ('rf', RandomForestClassifier(random_state=42))
])
rf_default_pipe.fit(X_train_scaled, y_train)

# Skorları da sızıntısız orijinal veri üzerinden kontrol ediyoruz
default_train_score = rf_default_pipe.score(X_train_scaled, y_train)
default_test_score = rf_default_pipe.score(X_test_scaled, y_test)


# ADIM 2: HİPERPARAMETRE OPTİMİZASYONU (Pipeline İçinde SMOTE ile)
# Parametre isimlerinin başına algoritmanın ismini (rf__) ekliyoruz ki Pipeline tanısın
rf_param_grid = {
    'rf__n_estimators': [50, 100, 200],
    'rf__max_depth': [None, 10, 20, 30],
    'rf__min_samples_split': [2, 5, 10],
    'rf__criterion': ['gini', 'entropy']
}

# Veri sızıntısını engellemek için SMOTE işlemini Pipeline içine alıyoruz
smote_pipeline = ImbPipeline([
    ('smote', SMOTE(random_state=42)),
    ('rf', RandomForestClassifier(random_state=42))
])

rf_random = RandomizedSearchCV(estimator=smote_pipeline,
                               param_distributions=rf_param_grid,
                               n_iter=10, cv=3, verbose=0, random_state=42)

#  SMOTE UYGULANMIŞ VERİYİ DEĞİL, ORİJİNAL VERİYİ VERİYORUZ (SMOTE'u içeride kendi yapacak)
rf_random.fit(X_train_scaled, y_train)
en_iyi_model = rf_random.best_estimator_

# Skorları da sızıntısız orijinal veri üzerinden kontrol ediyoruz
optimized_train_score = en_iyi_model.score(X_train_scaled, y_train)
optimized_test_score = en_iyi_model.score(X_test_scaled, y_test)


# ADIM 3: OVERFITTING KONTROLÜ VE SKORLARIN YAZDIRILMASI
print(f"-> DEFAULT Model Eğitim Skoru : % {default_train_score*100:.2f}")
print(f"-> DEFAULT Model Test Skoru   : % {default_test_score*100:.2f}")
gap = default_train_score - default_test_score
if gap > 0.05:
    print(f"   (Not: {gap*100:.1f} puanlık eğitim-test farkı Overfitting'e işaret ediyor!)\n")
else:
    print("   (Not: Eğitim ve test skorları birbirine yakın — belirgin bir Overfitting görülmüyor.)\n")

print(f"-> OPTİMİZE Model Eğitim Skoru: % {optimized_train_score*100:.2f}")
print(f"-> OPTİMİZE Model Test Skoru  : % {optimized_test_score*100:.2f}")
print(f"   Bulunan En İyi Parametreler: {rf_random.best_params_}\n")


# ADIM 4: DETAYLI SINIFLANDIRMA RAPORU (Precision, Recall, F1)
y_pred_best = en_iyi_model.predict(X_test_scaled)
y_probs = en_iyi_model.predict_proba(X_test_scaled)[:, 1]

print("OPTİMİZE EDİLMİŞ MODELİN SINIFLANDIRMA RAPORU (F1, Precision, Recall):")
print(classification_report(y_test, y_pred_best))


# ADIM 5: GÖRSELLEŞTİRME  (Confusion Matrix, ROC, Feature Importance)
sns.set_theme(style="whitegrid")
fig, axes = plt.subplots(1, 3, figsize=(24, 7))

# Grafik A: Karmaşıklık Matrisi
sns.heatmap(confusion_matrix(y_test, y_pred_best), annot=True, fmt='d', cmap='Blues', ax=axes[0], cbar=False)
axes[0].set_title('Optimize Rastgele Orman: Karmaşıklık Matrisi')
axes[0].set_xlabel('Tahmin Edilen')
axes[0].set_ylabel('Gerçek Değer')

# Grafik B: ROC Eğrisi
fpr, tpr, _ = roc_curve(y_test, y_probs)
axes[1].plot([0, 1], [0, 1], 'k--')
axes[1].plot(fpr, tpr, label=f'AUC: {roc_auc_score(y_test, y_probs):.4f}', color='#ff7f0e', linewidth=2)
axes[1].set_title('ROC Eğrisi')
axes[1].legend(loc="lower right")

# Grafik C: Özellik Önemi (Feature Importance)
# Pipeline içindeki Random Forest ('rf') adımına ulaşarak önemleri çekiyoruz
importances = en_iyi_model.named_steps['rf'].feature_importances_
imp_df = pd.DataFrame({'Özellik': X.columns, 'Önem': importances}).sort_values(by='Önem', ascending=False)
sns.barplot(x='Önem', y='Özellik', data=imp_df, ax=axes[2], palette='mako')
axes[2].set_title('Özellik Önem Düzeyi (Feature Importance)')

plt.tight_layout()
plt.show()


# ÖZGÜN DEĞER: SHAP İLE AÇIKLANABİLİR YAPAY ZEKA
import shap
import numpy as np
import matplotlib.pyplot as plt

shap.initjs()

print("\nSHAP İLE MODEL KARARLARININ AÇIKLANMASI\n")

# SHAP hesaplamaları büyük verilerde yavaş olabilir, test setinden 500 rastgele örneklem alıyoruz.
X_test_sample = pd.DataFrame(X_test_scaled, columns=X.columns).sample(n=500, random_state=42)

# Lider Modelimiz (Optimize edilmiş en_iyi_model) için SHAP Explainer oluşturma
explainer = shap.TreeExplainer(en_iyi_model.named_steps['rf'])
shap_values = explainer.shap_values(X_test_sample)

# 1. GLOBAL AÇIKLAMA (Summary Plot - Genel Özellik Etkileri)
print("\nSHAP GLOBAL AÇIKLAMA (Özelliklerin Genel Etkisi)\n")

# Boyut (Dimension) Hatasını Önleyen Dinamik Yapı
if isinstance(shap_values, list):
    shap_data_global = shap_values[1]
elif isinstance(shap_values, np.ndarray) and len(shap_values.shape) == 3:
    # 3 Boyutlu ise: Tüm satırlar, Tüm sütunlar, Sınıf 1 (Gama)
    shap_data_global = shap_values[:, :, 1]
else:
    shap_data_global = shap_values

# Yeni bir figür oluşturuyoruz
plt.figure(figsize=(10, 6))

# Grafiği çizdiriyoruz
shap.summary_plot(shap_data_global, X_test_sample, show=False)

plt.title("SHAP Özet Grafiği (Hangi Sütun Modele Ne Karar Verdiriyor?)", fontsize=14)
plt.tight_layout()
plt.show()

# 2. LOCAL AÇIKLAMA (Force Plot - Tekil Karar İncelemesi)
print("\nSHAP LOCAL AÇIKLAMA (Tekil Veri Noktaları İçin Kararlar)")
print("Aşağıdaki grafikler, modelin rastgele seçilen 3 FARKLI teleskop sinyaline bakarken neden Gama (1) veya Hadron (0) kararı verdiğini göstermektedir.\n")

for i in range(3):
    print(f"\n-> Örnek Sinyal {i+1} Analizi:")

    #Expected Value (Beklenen Değer) Hatasını Önleme
    if isinstance(explainer.expected_value, (list, np.ndarray)) and len(explainer.expected_value) > 1:
        base_val = explainer.expected_value[1]
    else:
        base_val = explainer.expected_value

    #Tekil Veri Noktası İçin Boyut Kontrolü
    if isinstance(shap_values, list):
        shap_val_local = shap_values[1][i]
    elif isinstance(shap_values, np.ndarray) and len(shap_values.shape) == 3:
        shap_val_local = shap_values[i, :, 1]
    else:
        shap_val_local = shap_values[i]

    feature_val = X_test_sample.iloc[i]

    #Matplotlib=True kullanırken çakışmayı önlemek için show=True yapıyoruz
    shap.force_plot(
        base_value=base_val,
        shap_values=shap_val_local,
        features=feature_val,
        matplotlib=True,
        show=True
    )

print("\nSHAP Analizi Başarıyla Tamamlandı.")

# 6. YAPAY SİNİR AĞLARI (YSA / ANN) MODELLEMESİ (Dropout & Early Stopping)

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.callbacks import EarlyStopping
from sklearn.metrics import confusion_matrix, classification_report, roc_curve, roc_auc_score
from sklearn.model_selection import train_test_split

print("YAPAY SİNİR AĞI (YSA) MODELİ EĞİTİLİYOR\n")

"""
Metodolojik Savunma: Yapay Sinir Ağları (TensorFlow/Keras) mimarisi gereği Scikit-Learn veya
Imblearn Pipeline'ları ile doğrudan (ve stabil) uyumlu çalışmaz. Bu nedenle YSA eğitiminde SMOTE
işlemi hücre içinde statik olarak uygulanmış, ardından test setine kesinlikle dokunulmadan kendi
içinde bir doğrulama (validation) setine ayrılmıştır. Sızıntı (Leakage) söz konusu değildir.
"""

from sklearn.model_selection import train_test_split
from imblearn.over_sampling import SMOTE

# ADIM 1: Veriyi ÖNCE bölüyoruz (Sızıntıyı önlemek için)
X_train_sub, X_val_nn, y_train_sub, y_val_nn = train_test_split(
    X_train_scaled, y_train, test_size=0.2, random_state=42)

# SMOTE işlemini SADECE ayırdığımız eğitim alt-kümesine uyguluyoruz
# Böylece Validation (Doğrulama) setine sentetik veri sızmamış oluyor.
smote_nn = SMOTE(random_state=42)
X_train_nn, y_train_nn = smote_nn.fit_resample(X_train_sub, y_train_sub)

# ADIM 2: MODEL MİMARİSİ
ysa_model = Sequential()
ysa_model.add(Dense(units=32, activation='relu', input_shape=(X_train_nn.shape[1],)))
ysa_model.add(Dropout(0.3)) #Nöronların %30'u kapatılarak ezberleme engellenir
ysa_model.add(Dense(units=16, activation='relu'))
ysa_model.add(Dropout(0.3))
ysa_model.add(Dense(units=1, activation='sigmoid'))

ysa_model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# ADIM 3: ERKEN DURDURMA (Early Stopping)
early_stop = EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)

# ADIM 4: EĞİTİM SÜRECİ
history = ysa_model.fit(
    X_train_nn, y_train_nn,
    epochs=50,
    batch_size=32,
    validation_data=(X_val_nn, y_val_nn),
    verbose=1,
    callbacks=[early_stop]
)

# ADIM 5: TAHMİNLER VE SINIFLANDIRMA RAPORU
y_pred_probs = ysa_model.predict(X_test_scaled, verbose=0).flatten()
y_pred = (y_pred_probs > 0.5).astype(int) # 0.5 eşiğine göre 1 veya 0 yapıyoruz

print("\nYSA MODELİ SINIFLANDIRMA RAPORU:")
print(classification_report(y_test, y_pred))

# ADIM 6: GÖRSELLEŞTİRME
sns.set_theme(style="whitegrid")
fig, axes = plt.subplots(2, 2, figsize=(16, 12))

best_epoch = np.argmin(history.history['val_loss'])

# Grafik 1: Accuracy (Doğruluk)
axes[0, 0].plot(history.history['accuracy'], label='Eğitim Doğruluğu', color='#1f77b4', linewidth=2)
axes[0, 0].plot(history.history['val_accuracy'], label='Doğrulama (Validation)', color='#ff7f0e', linewidth=2)
axes[0, 0].axvline(x=best_epoch, color='red', linestyle='--', label=f'Optimum Nokta (Epoch {best_epoch+1})')
axes[0, 0].set_title('YSA Model Doğruluğu (Accuracy)', fontsize=13)
axes[0, 0].set_xlabel('Epoch (Eğitim Turu)')
axes[0, 0].set_ylabel('Doğruluk Oranı')
axes[0, 0].legend()

# Grafik 2: Loss (Kayıp)
axes[0, 1].plot(history.history['loss'], label='Eğitim Kaybı (Loss)', color='#1f77b4', linewidth=2)
axes[0, 1].plot(history.history['val_loss'], label='Doğrulama (Validation)', color='#ff7f0e', linewidth=2)
axes[0, 1].axvline(x=best_epoch, color='red', linestyle='--', label=f'Optimum Nokta (Epoch {best_epoch+1})')
axes[0, 1].set_title('YSA Model Kaybı (Loss)', fontsize=13)
axes[0, 1].set_xlabel('Epoch (Eğitim Turu)')
axes[0, 1].set_ylabel('Kayıp Değeri')
axes[0, 1].legend()

# Grafik 3: Confusion Matrix
sns.heatmap(confusion_matrix(y_test, y_pred), annot=True, fmt='d', cmap='Blues', ax=axes[1, 0], cbar=False)
axes[1, 0].set_title("YSA - Karmaşıklık Matrisi (Confusion Matrix)", fontsize=13)
axes[1, 0].set_xlabel("Tahmin Edilen Sınıf")
axes[1, 0].set_ylabel("Gerçek Sınıf")

# Grafik 4: ROC Eğrisi
fpr, tpr, _ = roc_curve(y_test, y_pred_probs)
auc_score = roc_auc_score(y_test, y_pred_probs)
axes[1, 1].plot(fpr, tpr, label=f"AUC Skoru: {auc_score:.4f}", color='purple', linewidth=2)
axes[1, 1].plot([0,1],[0,1],'k--')
axes[1, 1].set_title("YSA - ROC Eğrisi", fontsize=13)
axes[1, 1].set_xlabel("Yanlış Pozitif Oranı (FPR)")
axes[1, 1].set_ylabel("Doğru Pozitif Oranı (TPR)")
axes[1, 1].legend(loc="lower right")

plt.tight_layout()
plt.show()

# 7. GÖZETİMSİZ ÖĞRENME (KÜMELEME) VE GERÇEK VERİ KIYASLAMASI

from sklearn.cluster import KMeans
from sklearn.metrics import adjusted_rand_score # İyileştirme: ARI Skoru için kütüphane eklendi
from scipy.cluster.hierarchy import dendrogram, linkage


print("Gözetimsiz Öğrenme (Kümeleme) Algoritmaları Çalıştırılıyor...\n")

# Dendrogram için veri sınırlandırması (Bellek çökmesini önlemek için)
X_cluster = X_train_scaled[:2000]

wcss = []
k_araligi = range(1, 11)

for i in k_araligi:
    kmeans = KMeans(n_clusters=i, init='k-means++', random_state=42, n_init=10)
    kmeans.fit(X_cluster)
    wcss.append(kmeans.inertia_)

hc_linkage = linkage(X_cluster, method='ward')

# K-Means Modeli
kmeans_final = KMeans(n_clusters=2, random_state=42, n_init=10)
kmeans_kumeler = kmeans_final.fit_predict(X_cluster)

# GÖRSELLEŞTİRME PANELİ
sns.set_theme(style="whitegrid")
fig, axes = plt.subplots(1, 2, figsize=(16, 6))

axes[0].plot(k_araligi, wcss, marker='o', linestyle='--', color='red', linewidth=2)
axes[0].set_title('K-Means: Dirsek Yöntemi (Elbow Method)', fontsize=14)
axes[0].set_xlabel('Küme Sayısı (k)', fontsize=12)
axes[0].set_ylabel('WCSS', fontsize=12)

dendrogram(hc_linkage, truncate_mode='lastp', p=12, leaf_rotation=45, ax=axes[1])
axes[1].set_title('Hiyerarşik Kümeleme: Dendrogram', fontsize=14)
axes[1].set_xlabel('Küme Endeksleri / Boyutları', fontsize=12)
axes[1].set_ylabel('Uzaklık (Öklid)', fontsize=12)

plt.tight_layout()
plt.show()


# KÜMELERİN GERÇEK SINIFLARLA KIYASLANMASI
print("K-MEANS KÜMELERİ İLE GERÇEK SINIFLARIN KARŞILAŞTIRILMASI")

gercek_etiketler = y_train[:2000].values

karsilastirma_df = pd.DataFrame({
    'Gerçek Sınıf (1: Gama, 0: Hadron)': gercek_etiketler,
    'K-Means Kümesi': kmeans_kumeler
})

print("Çapraz Tablo (Crosstab):")
display(pd.crosstab(karsilastirma_df['Gerçek Sınıf (1: Gama, 0: Hadron)'], karsilastirma_df['K-Means Kümesi']))

ari_skoru = adjusted_rand_score(gercek_etiketler, kmeans_kumeler)
print(f"\nDüzeltilmiş Rand İndeksi (ARI Skoru): {ari_skoru:.4f}")

"""Gözetimsiz öğrenme analizimizde ARI skorunun 0.0076 çıkması, K-Means algoritmasının hedef değişkeni (Gama/Hadron) ayırmada başarısız olduğunu göstermektedir. Bunun sebebi, uzay teleskobu verilerinin doğrusal ve küresel (spherical) kümeler oluşturmaması, aksine karmaşık ve iç içe geçmiş bir uzaya sahip olmasıdır. Bu durum, veri setimizde neden K-Means gibi basit mesafe tabanlı algoritmalar yerine, Rastgele Orman (Random Forest) gibi karmaşık karar sınırları çizebilen gözetimli öğrenme modellerinin çok daha başarılı olduğunu bilimsel olarak kanıtlamaktadır."""

# 8. EK ANALİZ: PCA İLE BOYUT İNDİRGEME VE KAPSAMLI MODEL KIYASLAMASI

from sklearn.decomposition import PCA
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier

print("ÖZGÜN DEĞER: PCA (TEMEL BİLEŞEN ANALİZİ)")
print("\nMetodolojik Not: PCA (Temel Bileşen Analizi), boyut indirgemenin algoritmalar üzerindeki 'saf' ve \ndoğal etkisini gözlemlemek amacıylabilinçli olarak SMOTE uygulanmamış orijinal veri seti üzerinde gerçekleştirilmiştir.")

# AŞAMA 1: Kümülatif Varyans Grafiği

pca_full = PCA(random_state=42)
pca_full.fit(X_train_scaled)

plt.figure(figsize=(8, 5))
plt.plot(range(1, len(pca_full.explained_variance_ratio_) + 1),
         np.cumsum(pca_full.explained_variance_ratio_), marker='o', linestyle='--', color='b')
plt.axhline(y=0.95, color='r', linestyle='-', label='%95 Varyans Sınırı')
plt.xlabel("Bileşen (Özellik) Sayısı", fontsize=12)
plt.ylabel("Kümülatif Açıklanan Varyans", fontsize=12)
plt.title("PCA - Kümülatif Açıklanan Varyans Grafiği", fontsize=14)
plt.legend()
plt.grid(True, alpha=0.5)
plt.tight_layout()
plt.show()


# AŞAMA 2: %95 Varyansı Koruyan PCA Dönüşümü
# Verideki bilginin %95'ini koruyarak boyut indirgiyoruz

pca_95 = PCA(n_components=0.95, random_state=42)
X_train_pca = pca_95.fit_transform(X_train_scaled)
X_test_pca = pca_95.transform(X_test_scaled)

orijinal_boyut = X_train_scaled.shape[1]
yeni_boyut = X_train_pca.shape[1]

print(f"\nOrijinal Değişken Sayısı: {orijinal_boyut}")
print(f"Bilginin %95'ini Koruyan Temel Bileşen Sayısı: {yeni_boyut}")
print(f"YORUM: Veri %95 oranında açıklanabilirliğini korurken {orijinal_boyut} boyuttan {yeni_boyut} boyuta düşürülmüştür")


# AŞAMA 3: Orijinal Veri vs PCA Verisi Model Karşılaştırması
print("\nOrijinal Veri ve PCA Uygulanmış Veri Üzerinde Modeller Karşılaştırılması:")

# Karşılaştırılacak Modeller
pca_modeller = {
    "Logistic Regression": LogisticRegression(random_state=42),
    f"K-Nearest Neighbors (k={best_k})": KNeighborsClassifier(n_neighbors=best_k),
    "Random Forest": RandomForestClassifier(n_estimators=100, random_state=42)
}

pca_karsilastirma_sonuclari = []

for isim, model in pca_modeller.items():
    # 1. Orijinal Veri ile Eğitim ve Test
    model.fit(X_train_scaled, y_train)
    y_pred_normal = model.predict(X_test_scaled)
    acc_normal = accuracy_score(y_test, y_pred_normal)

    # 2. PCA Uygulanmış Veri ile Eğitim ve Test
    model.fit(X_train_pca, y_train)
    y_pred_pca = model.predict(X_test_pca)
    acc_pca = accuracy_score(y_test, y_pred_pca)

    # Sonuçları Kaydetme
    pca_karsilastirma_sonuclari.append({
        "Model": isim,
        "Orijinal Veri Doğruluğu": round(acc_normal, 4),
        "PCA Verisi Doğruluğu (%95)": round(acc_pca, 4),
        "Fark": round(acc_normal - acc_pca, 4)
    })

# DataFrame'e çevir ve göster
pca_df = pd.DataFrame(pca_karsilastirma_sonuclari)
display(pca_df)
print("\nPCA Analizi Tamamlandı")

# 9. PROJE SONUCU VE GENEL DEĞERLENDİRME

print("MAGIC GAMMA TELESCOPE PROJESİ - SONUÇLARI")

print("""
1. Proje kapsamında Uzay Teleskobu sinyalleri (Gama ve Hadron) 6 klasik + 1 derin öğrenme modeli ile analiz edilmiştir.
2. Dengesiz veri problemi (Class Imbalance), çapraz doğrulama içerisine sızmayı engelleyecek şekilde
   gelişmiş 'Pipeline SMOTE' mimarisi ile çözülmüştür.
3. PCA ile verinin %95 varyansı korunarak boyut indirgenmiş ve hesaplama maliyetleri düşürülmüştür.
4. Gözetimsiz öğrenmede ARI skorunun düşük çıkması, verinin karmaşık karar sınırlarına sahip olduğunu
   ve gözetimli makine öğrenmesine ihtiyaç duyduğunu bilimsel olarak kanıtlamıştır.

LİDER MODEL:
Optimizasyon testleri sonucunda en başarılı model 'SMOTE Pipeline entegreli Optimize Rastgele Orman (Random Forest)' olmuştur.
Model, Gama sinyallerini yüksek Recall oranı ile yakalayarak projenin fiziksel bağlamındaki 'teleskop zamanı israfını önleme'
hedefini başarıyla yerine getirmiştir. Modelin kararları SHAP (Explainable AI) ile şeffaf bir şekilde açıklanmıştır.
""")